In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [15]:
area = df.drop('price',axis='columns')

In [17]:
area

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [ ]:
price = df.drop('Area',axis='columns')

In [12]:
x

0    2600
1    3000
2    3200
3    3600
4    4000
Name: area, dtype: int64

In [5]:
x

0    2600
1    3000
2    3200
3    3600
4    4000
Name: area, dtype: int64

In [6]:
y

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [8]:
from sklearn import linear_model

In [19]:
model = linear_model.LinearRegression()

In [20]:
model.fit(area,df.price)

LinearRegression()

In [21]:
model.predict([[2600]])

array([533664.38356164])

In [22]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [23]:
model.predict([[100]])

array([194195.20547945])

In [24]:
model.intercept_

180616.43835616432

In [25]:
model.coef_

array([135.78767123])

In [26]:
# mx+c


135.78767123*100+180616.43835616432

194195.20547916432

In [34]:
import numpy as np

In [42]:
arr = np.array([334,45,34,34,45,34,23,45])

In [43]:
area_to_predict = pd.DataFrame(arr)

In [44]:
area_to_predict

0
0  334
1   45
2   34
3   34
4   45
5   34
6   23
7   45

In [45]:
price_predicted = model.predict(area_to_predict)

In [48]:
# column added
area_to_predict['price'] = price_predicted

In [49]:
area_to_predict

0          price
0  334  225969.520548
1   45  186726.883562
2   34  185233.219178
3   34  185233.219178
4   45  186726.883562
5   34  185233.219178
6   23  183739.554795
7   45  186726.883562

In [50]:
income_df = pd.read_csv('income.csv')

In [52]:
income_df.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [54]:
income_df

year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997             17310.757750
28  1998             16622.671870
29  1999             17581.024140
30  2000             18987.382410
31  2001             18601.397240
32  2002             19232.175560
33  2003             22739.426280
34  2004             25719.147150
35  2005             29198.055690
36  2006             32738.262900
37  2007             36144.481220
38  2008             37446.486090
39  2009             32755.176820
40  2010             38420.522890
41  2011             42334.711210
42  2012             42665.255970
43  2013             42676.468370
44  2014             41039.893600
45  2015             35175.188980
46  2016             34229.193630